### ISSUE TITLE
New Syncthing.download.recipe appcast URL broken

### ISSUE THREAD

**Issue by fseesink** [autopkg/ctueck-recipes#1]
Started getting an error from this recipe.  Digging into it, seems the appcast URL change a month ago is the cause.

That is,

OLD URL:  https://upgrades.syncthing.net/syncthing-macos/appcast.xml
still shows data.

NEW URL:  https://upgrades.syncthing.net/appcast.xml
kicks back 404 error.

Not sure if this is temporary on the part of the Syncthing for Mac devs or what, but thought I should mention it.

**Comment by ctueck** [comment]
Ok, quite late, but I coincidentally realised now that I had noticed and fixed the issue in 3358d7d, even though I didn't see your comment/issue. :)

To be honest, I don't remember exactly why/how I thought the appcast URL had changed, but maybe there was a temporary issue with the original (and correct) one.
